### ISSUE TITLE
Can't support this cookie file from curl command

### ISSUE THREAD

**Issue by linhua55** [shichao-an/115wangpan#18]
➜  ~  cat /tmp/aa.cookie
![screenshot_2015-04-15_20-13-10](https://cloud.githubusercontent.com/assets/6326116/7158366/f27ae672-e3ab-11e4-9521-39899c353393.png)

File locate at 
http://pan.baidu.com/s/1jGzO90a

This file come from this command.
➜  ~  rm /tmp/aa.cookie && curl 'http://passport.115.com/?ct=open_login&ac=api_login&t=qq&goto=&code=9AD253F2306CB0BC33D464C372928724' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'  -H 'Accept-Language: zh-CN,en-US;q=0.7,en;q=0.3' -H 'Connection: keep-alive'  -H 'DNT: 1' -H 'Host: passport.115.com' -H 'Referer: http://openapi.qzone.qq.com/oauth/show?which=ConfirmPage&display=pc&redirect_uri=http%3A%2F%2Fpassport.115.com%2F%3Fct%3Dopen_login%26ac%3Dapi_login%26t%3Dqq%26goto%3D&response_type=code&oauth_token=&client_id=100229269' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0'  -c /tmp/aa.cookie  -b PHPSESSID=bo72eikeo6ijn9oibul0na5mn0 > /dev/null && cat /tmp/aa.cookie

I use these commands to load.

> from u115 import API
> api = API(auto_logout=False,persistent=True,cookies_filename='/tmp/aa.cookie',cookies_type='MozillaCookieJar')
> api.cookies
> str(api.cookies).count('=')

Only load three cookie name,It ignore the row which contain string "#HttpOnly_.115.com".

    My python version
    Python 3.4.3

Sorry for my english.

**Comment by shichao-an** [comment]
Hi, @linhua55 ,

It seems MozillaCookieJar never supports "HttpOnly", which is the cookies.txt format (though it is used by curl), please refer to: http://bugs.python.org/issue2190

Also, currently Python 3.4 is not fully supported and tested, due to an issue (not identified as bug by upstream, http://bugs.python.org/issue23841) related to weakref in the upstream. Please refer to this https://github.com/kennethreitz/requests/issues/2303. Maybe supported in the future
